### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [MooseDojo/apt2#44] opened 2017-12-07 11:45 UTC
hi i got this message when i use apt2.py Verion: 1.0.1
i select  an option: 4 to Quit and i got this

[?] Select an option: 4
[4]
*** print_tb:
  File "apt2.py", line 15, in main
    framework.run(sys.argv[1:])

*** print_exception:
Traceback (most recent call last):
  File "apt2.py", line 15, in main
    framework.run(sys.argv[1:])
  File "/root/Desktop/apt2/core/framework.py", line 723, in run
    kb.save(self.kbSaveFile)
NameError: global name 'Keystore' is not defined

*** print_exc:
Traceback (most recent call last):
  File "apt2.py", line 15, in main
    framework.run(sys.argv[1:])
  File "/root/Desktop/apt2/core/framework.py", line 723, in run
    kb.save(self.kbSaveFile)
  File "/root/Desktop/apt2/core/keystore.py", line 106, in save
    Utils.writeFile(Keystore.dump(), filename)
NameError: global name 'Keystore' is not defined

 My OS is Kali Linux Linux kali 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux
Python 2.7.14

Thank you  :)

**Comment by tatanus** [comment] 2017-12-10 21:35
while I look into what the cause was, can you provide the commandline you used to execute apt2?

**Comment by wermaxta** [comment] 2017-12-12 17:00
git clone https://github.com/MooseDojo/apt2.git
cd apt2
python setup install
pip install cython
pip install unqlite
after that i start
./apt2.py
then i Select an option: 4
and i got this

*** print_tb:
  File "./apt2.py", line 15, in main
    framework.run(sys.argv[1:])


*** print_exception:
Traceback (most recent call last):
  File "./apt2.py", line 15, in main
    framework.run(sys.argv[1:])
  File "/root/Desktop/apt2/core/framework.py", line 723, in run
    kb.save(self.kbSaveFile)
NameError: global name 'Keystore' is not defined


*** print_exc:
Traceback (most recent call last):
  File "./apt2.py", line 15, in main
    framework.run(sys.argv[1:])
  File "/root/Desktop/apt2/core/framework.py", line 723, in run
    kb.save(self.kbSaveFile)
  File "/root/Desktop/apt2/core/keystore.py", line 106, in save
    Utils.writeFile(Keystore.dump(), filename)
 
i test it with 
python apt2.py
i got same error message
Thank you

**Comment by acompton-r7** [comment] 2017-12-14 21:27
sorry for the delay, it should be fixed now

**Comment by wermaxta** [comment] 2017-12-16 18:03
Thank you :)

**Closed** 2018-01-01 16:59 UTC
